library(ggplot2)
library(dplyr)
library(pillar)
install.packages("plotly")
library(plotly)
#Task B1:
the_wall_street_data<- read.csv(file.choose())
head(the_wall_street_data)
tail(the_wall_street_data)
summary(the_wall_street_data)
summary(the_wall_street_data$The.Wall.Street.Journal.Parade.of.Climate.Lies)
colnames(the_wall_street_data)<- c("page_name","post_id","page_id","post_name","message","description","caption","post_type","status_type","likes_count","comments_count","shares_count","love_count","love_count","haha_count","sad_count","thankful_count","angry_count","post_link","picture","posted_at") 
colnames(the_wall_street_data)
head(the_wall_street_data)
boxplot(the_wall_street_data$comments_count, xlab = "number of comments", ylab = "comments_count")
boxplot(the_wall_street_data$comments_count,ylab = "Comments_count")
summary(the_wall_street_data$comments_count)
min(the_wall_street_data$comments_count)
max(the_wall_street_data$comments_count)
distinct(the_wall_street_data)
unique(the_wall_street_data)
boxplot(the_wall_street_data$comments_count>1000,xlab= "number of comments" ,ylab = "comments_count")
the_wall_street_data_1 <- distinct(the_wall_street_data)
head(the_wall_street_data_1)
the_wall_street_data[!duplicated(the_wall_street_data), ]
median(the_wall_street_data$post_type, na.rm = FALSE)
median(the_wall_street_data$comments_count, na.rm = F)
#Task B2:
abc_news_1 <- read.csv(file.choose())
colnames(abc_news_1)<- c("page_name","post_id","page_id","post_name","message","description","caption","post_type","status_type","likes_count","comments_count","shares_count","love_count","love_count","haha_count","sad_count","thankful_count","angry_count","post_link","picture","posted_at")
col(abc_news_1)
barplot(abc_news_1$likes_count)
trump_data <- read.csv(file.choose())
colnames(trump_data)<- c("page_name","post_id","page_id","post_name","message","description","caption","post_type","status_type","likes_count","comments_count","shares_count","love_count","love_count","haha_count","sad_count","thankful_count","angry_count","post_link","picture","posted_at")
colnames(trump_data)
colnames(trump_data)
barplot(trump_data$likes_count)
days <- c("MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN")
days
as.numeric(trump_data$posted_at)
barplot(trump_data$post_id, xlab= "mon    tue    wed    thu   fri    sat   sun",ylab = "reactions_count", width=c(2,3,1,3,2,0.5,2),space=c(2,3,1,3,2,0.5,2),horiz = F )
barplot(height =trump_data$comments_count, xlab = "mon    tue    wed    thu   fri    sat   sun" , ylab = "reactions_count",col = rgb(0.2,0.4,0.6,0.6),width = c(0.1,0.2,0.3,1.5,0.5,2), horiz = F )
counts <-table(trump_data$comments_count,trump_data$shares_count)
barplot(counts, main="Number of Reactions", xlab=  "mon    tue    wed    thu   fri    sat   sun", col=c("darkblue","red"),legend = rownames(counts),beside=TRUE)
barplot(height=trump_data$shares_count, xlab= " 1   2   3   4   5   6    7    8    9    10    11    12 ", ylab ="reaction_counts", horiz = F)
barplot(trump_data$comments_count, xlab= " 1   2   3   4   5   6    7    8    9    10    11    12 ", ylab ="reaction_counts", horiz = F)